version: '3.9'

services:
  # Frontend-приложение
  frontend:
    image: allower99/frontend:latest
    container_name: frontend
    hostname: frontend
    ports:
      - "80:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - monitoring_net
